#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ToolHandlerKind {
    ShellCommand,
    Read,
    Write,
    Edit,
    Glob,
    Grep,
    ApplyPatch,
    Plan,
    Question,
    WebFetch,
    WebSearch,
    Skill,
    Lsp,
    Invalid,
    ExecCommand,
    WriteStdin,
    ToolSearch,
    Ipython,
}
