use std::collections::BTreeMap;
use std::fs;
use std::io;
use std::path::Path;

use schemars::JsonSchema;
use schemars::schema::RootSchema;
use serde::Serialize;
use ts_rs::Config;
use ts_rs::TS;

use crate::native::item::ContextCategoryId;
use crate::native::item::ContextCategoryUsage;
use crate::native::item::ContextOccupancy;
use crate::native::rpc_admin::ContextUsageReadParams;
use crate::native::rpc_admin::ContextUsageReadResult;
use crate::native::rpc_admin::McpListParams;
use crate::native::rpc_admin::McpListResult;
use crate::native::rpc_admin::McpServerInfo;
use crate::native::rpc_admin::McpSetEnabledParams;
use crate::native::rpc_admin::McpSetEnabledResult;
use crate::native::rpc_admin::McpToolEntry;
use crate::native::rpc_admin::McpToolsParams;
use crate::native::rpc_admin::McpToolsResult;
use crate::parse_command::ParsedCommand;
use crate::*;

const GENERATED_HEADER: &str = "\
/* eslint-disable */
// This file is generated by `cargo run -p devo-protocol --bin generate-native-ts`.
// Do not edit it manually.

";

const INDEX_TS: &str = "\
/* eslint-disable */
// This file is generated by `cargo run -p devo-protocol --bin generate-native-ts`.
// Do not edit it manually.

export * from \"./acp\";
export * as DevoProtocol from \"./protocol\";
";

const NATIVE_INDEX_TS: &str = "\
/* eslint-disable */
// This file is generated by `cargo run -p devo-protocol --bin generate-native-ts`.
// Do not edit it manually.

export * from \"./native\";
export * as NativeProtocol from \"./native\";
";

/// Generate the desktop-facing ACP TypeScript wire contract.
pub fn generate_acp_typescript() -> String {
    let cfg = Config::from_env();
    let mut output = String::from(GENERATED_HEADER);

    push_decl::<serde_json::Value>(&cfg, &mut output);
    push_decl::<SessionId>(&cfg, &mut output);
    push_decl::<TurnId>(&cfg, &mut output);

    push_decl::<AcpInitializeParams>(&cfg, &mut output);
    push_decl::<AcpInitializeResult>(&cfg, &mut output);
    push_decl::<AcpImplementation>(&cfg, &mut output);
    push_decl::<AcpEmptyAuthResult>(&cfg, &mut output);

    push_decl::<AcpClientCapabilities>(&cfg, &mut output);
    push_decl::<AcpFileSystemCapabilities>(&cfg, &mut output);
    push_decl::<AcpClientSessionCapabilities>(&cfg, &mut output);
    push_decl::<AcpSessionConfigOptionsCapabilities>(&cfg, &mut output);
    push_decl::<AcpBooleanConfigOptionCapabilities>(&cfg, &mut output);
    push_decl::<AcpAgentCapabilities>(&cfg, &mut output);
    push_decl::<AcpPromptCapabilities>(&cfg, &mut output);
    push_decl::<AcpMcpCapabilities>(&cfg, &mut output);
    push_decl::<AcpSessionCapabilities>(&cfg, &mut output);
    push_decl::<AcpSessionListCapabilities>(&cfg, &mut output);
    push_decl::<AcpSessionDeleteCapabilities>(&cfg, &mut output);
    push_decl::<AcpSessionAdditionalDirectoriesCapabilities>(&cfg, &mut output);
    push_decl::<AcpSessionResumeCapabilities>(&cfg, &mut output);
    push_decl::<AcpSessionCloseCapabilities>(&cfg, &mut output);
    push_decl::<AcpAuthCapabilities>(&cfg, &mut output);
    push_decl::<AcpLogoutCapabilities>(&cfg, &mut output);
    push_decl::<AcpAuthMethod>(&cfg, &mut output);

    push_decl::<AcpListSessionsParams>(&cfg, &mut output);
    push_decl::<AcpListSessionsResult>(&cfg, &mut output);
    push_decl::<AcpSessionInfo>(&cfg, &mut output);
    push_decl::<AcpNewSessionParams>(&cfg, &mut output);
    push_decl::<AcpNewSessionResult>(&cfg, &mut output);
    push_decl::<AcpLoadSessionParams>(&cfg, &mut output);
    push_decl::<AcpResumeSessionParams>(&cfg, &mut output);
    push_decl::<AcpLoadSessionResult>(&cfg, &mut output);
    push_decl::<AcpSessionActionParams>(&cfg, &mut output);
    push_decl::<AcpEmptyResult>(&cfg, &mut output);
    push_decl::<AcpPromptParams>(&cfg, &mut output);
    push_decl::<AcpPromptResult>(&cfg, &mut output);
    push_decl::<AcpStopReason>(&cfg, &mut output);
    push_decl::<AcpCancelParams>(&cfg, &mut output);
    push_decl::<AcpSetModeParams>(&cfg, &mut output);
    push_decl::<AcpSetConfigOptionParams>(&cfg, &mut output);
    push_decl::<AcpSetConfigOptionValue>(&cfg, &mut output);
    push_decl::<AcpSetConfigOptionValueType>(&cfg, &mut output);
    push_decl::<AcpSetConfigOptionResult>(&cfg, &mut output);

    push_decl::<AcpMcpServer>(&cfg, &mut output);
    push_decl::<AcpMcpServerHttpType>(&cfg, &mut output);
    push_decl::<AcpMcpServerSseType>(&cfg, &mut output);
    push_decl::<AcpMcpServerHttp>(&cfg, &mut output);
    push_decl::<AcpMcpServerSse>(&cfg, &mut output);
    push_decl::<AcpMcpServerStdio>(&cfg, &mut output);
    push_decl::<AcpHttpHeader>(&cfg, &mut output);
    push_decl::<AcpEnvVariable>(&cfg, &mut output);

    push_decl::<AcpSessionMode>(&cfg, &mut output);
    push_decl::<AcpSessionModeState>(&cfg, &mut output);

    push_decl::<AcpSessionConfigOptionCategoryKnown>(&cfg, &mut output);
    push_decl::<AcpSessionConfigOptionCategory>(&cfg, &mut output);
    push_decl::<AcpSessionConfigSelectOption>(&cfg, &mut output);
    push_decl::<AcpSessionConfigSelectGroup>(&cfg, &mut output);
    push_decl::<AcpSessionConfigSelectOptions>(&cfg, &mut output);
    push_decl::<AcpSessionConfigSelect>(&cfg, &mut output);
    push_decl::<AcpSessionConfigOption>(&cfg, &mut output);

    push_decl::<AcpContentBlock>(&cfg, &mut output);
    push_decl::<AcpRole>(&cfg, &mut output);
    push_decl::<AcpAnnotations>(&cfg, &mut output);
    push_decl::<AcpEmbeddedResource>(&cfg, &mut output);
    push_decl::<AcpTextResourceContents>(&cfg, &mut output);
    push_decl::<AcpBlobResourceContents>(&cfg, &mut output);

    push_decl::<AcpSessionNotification>(&cfg, &mut output);
    push_decl::<AcpSessionUpdate>(&cfg, &mut output);
    push_decl::<AcpRequestPermissionParams>(&cfg, &mut output);
    push_decl::<AcpRequestPermissionResponse>(&cfg, &mut output);
    push_decl::<AcpToolCallUpdate>(&cfg, &mut output);
    push_decl::<AcpToolCallLocation>(&cfg, &mut output);
    push_decl::<AcpPermissionOption>(&cfg, &mut output);
    push_decl::<AcpPermissionOptionKind>(&cfg, &mut output);
    push_decl::<AcpPermissionOutcome>(&cfg, &mut output);
    push_decl::<AcpCost>(&cfg, &mut output);
    push_decl::<AcpAvailableCommandInput>(&cfg, &mut output);
    push_decl::<AcpAvailableCommand>(&cfg, &mut output);
    push_decl::<AcpToolKind>(&cfg, &mut output);
    push_decl::<AcpToolCallStatus>(&cfg, &mut output);
    push_decl::<AcpToolCallContent>(&cfg, &mut output);
    push_decl::<AcpPlanEntry>(&cfg, &mut output);
    push_decl::<AcpPlanEntryPriority>(&cfg, &mut output);
    push_decl::<AcpPlanEntryStatus>(&cfg, &mut output);

    push_decl::<RequestUserInputOption>(&cfg, &mut output);
    push_decl::<RequestUserInputQuestion>(&cfg, &mut output);
    push_decl::<RequestUserInputArgs>(&cfg, &mut output);
    push_decl::<RequestUserInputAnswer>(&cfg, &mut output);
    push_decl::<RequestUserInputResponse>(&cfg, &mut output);

    push_decl::<AcpFsReadTextFileParams>(&cfg, &mut output);
    push_decl::<AcpFsReadTextFileResult>(&cfg, &mut output);
    push_decl::<AcpFsWriteTextFileParams>(&cfg, &mut output);

    output.push_str("export type AcpResumeSessionResult = AcpLoadSessionResult;\n");
    output.push_str("export type AcpCloseSessionParams = AcpSessionActionParams;\n");
    output.push_str("export type AcpDeleteSessionParams = AcpSessionActionParams;\n");
    output.push_str("export type AcpCloseSessionResult = AcpEmptyResult;\n");
    output.push_str("export type AcpDeleteSessionResult = AcpEmptyResult;\n");
    output.push_str("export type AcpSetModeResult = AcpEmptyResult;\n");
    output.push_str("export type AcpAuthenticateResult = AcpEmptyAuthResult;\n");
    output.push_str("export type AcpLogoutParams = AcpEmptyAuthResult;\n");
    output.push_str("export type AcpLogoutResult = AcpEmptyAuthResult;\n");

    output
}

/// Generate desktop-facing non-ACP Devo protocol TypeScript wire types.
pub fn generate_protocol_typescript() -> String {
    let cfg = Config::from_env();
    let mut output = String::from(GENERATED_HEADER);
    push_decl::<serde_json::Value>(&cfg, &mut output);
    push_decl::<SessionId>(&cfg, &mut output);
    push_decl::<TurnId>(&cfg, &mut output);
    push_decl::<ItemId>(&cfg, &mut output);
    push_decl::<QueueItemId>(&cfg, &mut output);

    push_decl::<SessionTitleState>(&cfg, &mut output);
    push_decl::<SessionTitleFinalSource>(&cfg, &mut output);
    push_decl::<TurnStatus>(&cfg, &mut output);
    push_decl::<TurnUsage>(&cfg, &mut output);
    push_decl::<crate::native::event::ModelQueryRetryPhase>(&cfg, &mut output);
    push_decl::<TurnFailedPayload>(&cfg, &mut output);
    push_decl::<StopReason>(&cfg, &mut output);
    push_decl::<ParsedCommand>(&cfg, &mut output);
    push_decl::<native::item::FileChangeEntry>(&cfg, &mut output);
    push_decl::<native::item::FileChangeKind>(&cfg, &mut output);

    push_decl::<ReasoningEffort>(&cfg, &mut output);
    push_decl::<crate::ReasoningLevelChoice>(&cfg, &mut output);
    push_decl::<ReasoningCapability>(&cfg, &mut output);
    push_decl::<ReasoningImplementation>(&cfg, &mut output);
    push_decl::<ReasoningVariantConfig>(&cfg, &mut output);
    push_decl::<ReasoningVariant>(&cfg, &mut output);

    push_decl::<SessionStartParams>(&cfg, &mut output);
    push_decl::<SessionStartResult>(&cfg, &mut output);
    push_decl::<SessionResumeParams>(&cfg, &mut output);
    push_decl::<SessionResumeResult>(&cfg, &mut output);
    push_decl::<SessionHistoryEntry>(&cfg, &mut output);
    push_decl::<native::rpc_session::SessionForkCut>(&cfg, &mut output);
    push_decl::<native::model::ModelBinding>(&cfg, &mut output);
    push_decl::<native::model::PermissionProfile>(&cfg, &mut output);
    push_decl::<native::session::SessionParent>(&cfg, &mut output);
    push_decl::<native::session::SessionStatus>(&cfg, &mut output);
    push_decl::<native::session::SessionFlag>(&cfg, &mut output);
    push_decl::<native::session::SessionSettings>(&cfg, &mut output);
    push_decl::<native::session::GitInfo>(&cfg, &mut output);
    push_decl::<native::usage::UsagePurpose>(&cfg, &mut output);
    push_decl::<native::usage::UsageCallOutcome>(&cfg, &mut output);
    push_decl::<native::usage::TokenUsage>(&cfg, &mut output);
    push_decl::<native::usage::Money>(&cfg, &mut output);
    push_decl::<native::usage::UsageTotals>(&cfg, &mut output);
    push_decl::<native::usage::PurposeUsage>(&cfg, &mut output);
    push_decl::<native::usage::SessionUsage>(&cfg, &mut output);
    push_decl::<native::session::Session>(&cfg, &mut output);
    push_decl::<native::rpc_session::SessionForkParams>(&cfg, &mut output);
    push_decl::<native::rpc_session::SessionForkResult>(&cfg, &mut output);
    // Keep the Native subscription event graph opaque in this compatibility
    // declaration file; the generated JSON Schema bundle remains precise.
    output.push_str(
        "export type SubscriptionId = string;\n\n\
export type EventCursor = { streamId: string, seq: bigint, };\n\n\
export type StreamSelector = { \"kind\": \"sessionsByCwd\", cwd: string, } | { \"kind\": \"session\", sessionId: SessionId, } | { \"kind\": \"backgroundTask\", itemId: ItemId, };\n\n\
export type StreamSnapshot = { streamId: string, barrierSeq: bigint, data: unknown, };\n\n\
export type EventEnvelope = { event: unknown, notification: unknown, };\n\n\
export type LiveItemSnapshot = { item: unknown, accumulated: Array<unknown>, };\n\n\
export type PendingControlRequest = { requestId: string, kind: string, item: unknown, };\n\n\
export type SubscriptionCreateParams = { selectors: Array<StreamSelector>, includeSnapshot: boolean, after?: Array<EventCursor>, };\n\n\
export type SubscriptionCreateResult = { subscriptionId: SubscriptionId, snapshots?: Array<StreamSnapshot>, replay?: Array<EventEnvelope>, recoverySnapshots?: Array<LiveItemSnapshot>, cursors: Array<EventCursor>, pendingControlRequests?: Array<PendingControlRequest>, };\n\n\
export type SubscriptionUpdateParams = { subscriptionId: SubscriptionId, selectors: Array<StreamSelector>, };\n\n\
export type SubscriptionAckParams = { subscriptionId: SubscriptionId, cursors: Array<EventCursor>, };\n\n\
export type SubscriptionUnsubscribeParams = { subscriptionId: SubscriptionId, };\n\n",
    );
    push_decl::<TurnFailureReason>(&cfg, &mut output);
    push_decl::<native::item::UserInput>(&cfg, &mut output);
    push_decl::<native::item::ImageDetail>(&cfg, &mut output);
    push_decl::<CollaborationMode>(&cfg, &mut output);
    push_decl::<TurnExecutionMode>(&cfg, &mut output);
    push_decl::<TurnStartParams>(&cfg, &mut output);
    push_decl::<native::turn::Turn>(&cfg, &mut output);
    push_decl::<native::turn::TurnKind>(&cfg, &mut output);
    push_decl::<native::turn::TurnStatus>(&cfg, &mut output);
    push_decl::<native::usage::TurnUsage>(&cfg, &mut output);
    push_decl::<native::usage::UsageTotals>(&cfg, &mut output);
    push_decl::<native::usage::Money>(&cfg, &mut output);
    push_decl::<native::error::AgentError>(&cfg, &mut output);
    push_decl::<native::error::FieldViolation>(&cfg, &mut output);
    push_decl::<crate::native::rpc_turn::TurnRecovery>(&cfg, &mut output);
    push_decl::<crate::native::rpc_turn::TurnRecoveryReadParams>(&cfg, &mut output);
    push_decl::<crate::native::rpc_turn::TurnRecoveryReadResult>(&cfg, &mut output);
    push_decl::<crate::native::rpc_turn::TurnResumeParams>(&cfg, &mut output);
    push_decl::<crate::native::rpc_turn::TurnResumeResult>(&cfg, &mut output);

    push_decl::<TurnInputDisposition>(&cfg, &mut output);
    push_decl::<native::rpc_session::SessionInterruptScope>(&cfg, &mut output);
    push_decl::<native::rpc_session::SessionInterruptParams>(&cfg, &mut output);
    push_decl::<native::rpc_session::SessionInterruptResult>(&cfg, &mut output);
    push_decl::<TurnKind>(&cfg, &mut output);
    push_decl::<WorkspaceChangeScope>(&cfg, &mut output);
    push_decl::<WorkspaceDiffDetail>(&cfg, &mut output);
    push_decl::<WorkspaceChangeViewStatus>(&cfg, &mut output);
    push_decl::<WorkspaceChangeCoverage>(&cfg, &mut output);
    push_decl::<WorkspaceChangeSetStatus>(&cfg, &mut output);
    push_decl::<WorkspaceChangedFileStatus>(&cfg, &mut output);
    push_decl::<WorkspaceCheckpointBackend>(&cfg, &mut output);
    push_decl::<WorkspaceChangeBase>(&cfg, &mut output);
    push_decl::<WorkspaceChangeAttribution>(&cfg, &mut output);
    push_decl::<WorkspaceChangedFile>(&cfg, &mut output);
    push_decl::<WorkspaceChangeStats>(&cfg, &mut output);
    push_decl::<WorkspaceChangeView>(&cfg, &mut output);
    push_decl::<native::rpc_workspace::WorkspaceChangesReadParams>(&cfg, &mut output);
    push_decl::<native::rpc_workspace::WorkspaceChangesReadResult>(&cfg, &mut output);
    push_decl::<native::event::WorkspaceChangeStatsNotification>(&cfg, &mut output);
    push_decl::<native::event::WorkspaceChangesUpdatedNotification>(&cfg, &mut output);

    push_decl::<ApprovalResponseParams>(&cfg, &mut output);
    push_decl::<ApprovalDecisionValue>(&cfg, &mut output);
    push_decl::<ApprovalScopeValue>(&cfg, &mut output);
    push_decl::<PermissionPreset>(&cfg, &mut output);

    push_decl::<SkillRecord>(&cfg, &mut output);
    push_decl::<SkillSource>(&cfg, &mut output);
    push_decl::<SkillScope>(&cfg, &mut output);
    push_decl::<SkillInterface>(&cfg, &mut output);
    push_decl::<SkillDependencies>(&cfg, &mut output);
    push_decl::<SkillToolDependency>(&cfg, &mut output);
    push_decl::<native::rpc_admin::SkillListParams>(&cfg, &mut output);
    push_decl::<native::rpc_admin::SkillListResult>(&cfg, &mut output);
    push_decl::<native::rpc_admin::SkillInfo>(&cfg, &mut output);
    push_decl::<native::rpc_admin::SkillSetEnabledParams>(&cfg, &mut output);
    push_decl::<native::rpc_admin::SkillSetEnabledResult>(&cfg, &mut output);

    push_decl::<McpListParams>(&cfg, &mut output);
    push_decl::<McpServerInfo>(&cfg, &mut output);
    push_decl::<McpListResult>(&cfg, &mut output);
    push_decl::<McpToolsParams>(&cfg, &mut output);
    push_decl::<McpToolEntry>(&cfg, &mut output);
    push_decl::<McpToolsResult>(&cfg, &mut output);
    push_decl::<McpSetEnabledParams>(&cfg, &mut output);
    push_decl::<McpSetEnabledResult>(&cfg, &mut output);
    push_decl::<ContextUsageReadParams>(&cfg, &mut output);
    push_decl::<ContextUsageReadResult>(&cfg, &mut output);
    push_decl::<ContextCategoryId>(&cfg, &mut output);
    push_decl::<ContextCategoryUsage>(&cfg, &mut output);
    push_decl::<ContextOccupancy>(&cfg, &mut output);

    push_decl::<ProviderWireApi>(&cfg, &mut output);
    push_decl::<InputModality>(&cfg, &mut output);
    push_decl::<ProviderModelVariant>(&cfg, &mut output);
    push_decl::<ProviderModelInfo>(&cfg, &mut output);
    push_decl::<ProviderInfo>(&cfg, &mut output);
    push_decl::<ModelCatalogEntry>(&cfg, &mut output);
    push_decl::<native::rpc_admin::ProviderListParams>(&cfg, &mut output);
    push_decl::<native::rpc_admin::ProviderListResult>(&cfg, &mut output);
    push_decl::<native::rpc_admin::ProviderUpsertParams>(&cfg, &mut output);
    push_decl::<native::rpc_admin::ProviderUpsertResult>(&cfg, &mut output);
    push_decl::<native::rpc_admin::ProviderDisconnectParams>(&cfg, &mut output);
    push_decl::<native::rpc_admin::ProviderDisconnectResult>(&cfg, &mut output);
    push_decl::<native::rpc_admin::ProviderModelRemoveParams>(&cfg, &mut output);
    push_decl::<native::rpc_admin::ProviderModelRemoveResult>(&cfg, &mut output);
    push_decl::<native::rpc_admin::ProviderValidateParams>(&cfg, &mut output);
    push_decl::<native::rpc_admin::ProviderValidateResult>(&cfg, &mut output);
    push_decl::<native::rpc_admin::ProviderDiscoverParams>(&cfg, &mut output);
    push_decl::<native::rpc_admin::ProviderDiscoverResult>(&cfg, &mut output);

    push_decl::<CommandExecTerminalSize>(&cfg, &mut output);
    push_decl::<CommandExecProgram>(&cfg, &mut output);
    push_decl::<CommandExecParams>(&cfg, &mut output);
    push_decl::<CommandExecResult>(&cfg, &mut output);
    push_decl::<CommandExecWriteParams>(&cfg, &mut output);
    push_decl::<CommandExecWriteResult>(&cfg, &mut output);
    push_decl::<CommandExecResizeParams>(&cfg, &mut output);
    push_decl::<CommandExecResizeResult>(&cfg, &mut output);
    push_decl::<CommandExecTerminateParams>(&cfg, &mut output);
    push_decl::<CommandExecTerminateResult>(&cfg, &mut output);
    push_decl::<CommandExecOutputStream>(&cfg, &mut output);
    push_decl::<CommandExecOutputDeltaPayload>(&cfg, &mut output);
    push_decl::<CommandExecExitedPayload>(&cfg, &mut output);

    push_decl::<ReferenceSearchId>(&cfg, &mut output);
    push_decl::<native::rpc_search::SearchStartParams>(&cfg, &mut output);
    push_decl::<native::rpc_search::SearchStartResult>(&cfg, &mut output);
    push_decl::<native::rpc_search::SearchUpdateParams>(&cfg, &mut output);
    push_decl::<native::rpc_search::SearchUpdateResult>(&cfg, &mut output);
    push_decl::<native::rpc_search::SearchCancelParams>(&cfg, &mut output);
    push_decl::<native::rpc_search::SearchCancelResult>(&cfg, &mut output);
    push_decl::<native::rpc_search::SearchSnapshot>(&cfg, &mut output);
    push_decl::<native::rpc_search::SearchResult>(&cfg, &mut output);
    push_decl::<native::rpc_search::SearchResultKind>(&cfg, &mut output);
    push_decl::<native::rpc_search::SearchFailedPayload>(&cfg, &mut output);

    push_decl::<AgentToolPolicy>(&cfg, &mut output);
    push_decl::<SpawnAgentParams>(&cfg, &mut output);
    push_decl::<SpawnAgentResult>(&cfg, &mut output);
    push_decl::<AgentMessageParams>(&cfg, &mut output);
    push_decl::<AgentMessageResult>(&cfg, &mut output);
    push_decl::<WaitAgentParams>(&cfg, &mut output);
    push_decl::<AgentMailboxMessage>(&cfg, &mut output);
    push_decl::<WaitAgentResult>(&cfg, &mut output);
    push_decl::<AgentOutputEventKind>(&cfg, &mut output);
    push_decl::<ParentAgentOutputEvent>(&cfg, &mut output);
    push_decl::<ParentSpawnAgentResult>(&cfg, &mut output);
    push_decl::<ParentAgentInfo>(&cfg, &mut output);
    push_decl::<ParentAgentListResult>(&cfg, &mut output);
    push_decl::<AgentInfo>(&cfg, &mut output);
    push_decl::<TaskId>(&cfg, &mut output);
    push_decl::<TaskState>(&cfg, &mut output);
    push_decl::<TaskKind>(&cfg, &mut output);
    push_decl::<AgentTaskMetadata>(&cfg, &mut output);
    push_decl::<CommandTaskMetadata>(&cfg, &mut output);
    push_decl::<TaskInfo>(&cfg, &mut output);
    push_decl::<AwaitTaskParams>(&cfg, &mut output);
    push_decl::<AwaitTaskResult>(&cfg, &mut output);
    push_decl::<ListTasksParams>(&cfg, &mut output);
    push_decl::<ListTasksResult>(&cfg, &mut output);
    push_decl::<CancelTaskParams>(&cfg, &mut output);
    push_decl::<CancelTaskResult>(&cfg, &mut output);
    push_decl::<AgentListParams>(&cfg, &mut output);
    push_decl::<AgentListResult>(&cfg, &mut output);
    push_decl::<AgentStatusParams>(&cfg, &mut output);
    push_decl::<CloseAgentParams>(&cfg, &mut output);
    push_decl::<CloseAgentResult>(&cfg, &mut output);

    push_decl::<RequestUserInputOption>(&cfg, &mut output);
    push_decl::<RequestUserInputQuestion>(&cfg, &mut output);
    push_decl::<RequestUserInputArgs>(&cfg, &mut output);
    push_decl::<RequestUserInputAnswer>(&cfg, &mut output);
    push_decl::<RequestUserInputResponse>(&cfg, &mut output);

    output
}

/// Generate the JSON Schema bundle used by the desktop SDK runtime validator.
pub fn generate_protocol_schema_json() -> String {
    let bundle = protocol_schema_bundle();
    serde_json::to_string_pretty(&bundle).expect("serialize desktop protocol schema")
}

/// Write generated ACP TypeScript wire types to `output_dir`.
pub fn write_acp_typescript_dir(output_dir: impl AsRef<Path>) -> io::Result<()> {
    let output_dir = output_dir.as_ref();
    if output_dir.exists() {
        fs::remove_dir_all(output_dir)?;
    }
    fs::create_dir_all(output_dir)?;
    fs::write(output_dir.join("acp.ts"), generate_acp_typescript())?;
    fs::write(
        output_dir.join("protocol.ts"),
        generate_protocol_typescript(),
    )?;
    fs::write(
        output_dir.join("schema.json"),
        generate_protocol_schema_json(),
    )?;
    fs::write(output_dir.join("index.ts"), INDEX_TS)?;
    Ok(())
}

fn push_decl<T: TS>(cfg: &Config, output: &mut String) {
    output.push_str("export ");
    output.push_str(&T::decl(cfg));
    output.push_str("\n\n");
}

#[derive(Debug, Clone, Default, Serialize)]
#[serde(rename_all = "camelCase")]
struct MethodSchemaBinding {
    #[serde(skip_serializing_if = "Option::is_none")]
    outgoing_request: Option<&'static str>,
    #[serde(skip_serializing_if = "Option::is_none")]
    outgoing_notification: Option<&'static str>,
    #[serde(skip_serializing_if = "Option::is_none")]
    incoming_result: Option<&'static str>,
    #[serde(skip_serializing_if = "Option::is_none")]
    incoming_notification: Option<&'static str>,
    #[serde(skip_serializing_if = "Option::is_none")]
    incoming_request: Option<&'static str>,
    #[serde(skip_serializing_if = "Option::is_none")]
    outgoing_response: Option<&'static str>,
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
struct ProtocolSchemaBundle {
    schemas: BTreeMap<String, RootSchema>,
    methods: BTreeMap<String, MethodSchemaBinding>,
}

fn protocol_schema_bundle() -> ProtocolSchemaBundle {
    let mut schemas = BTreeMap::new();
    let mut methods = BTreeMap::new();

    register_acp_schemas(&mut schemas, &mut methods);
    register_devo_protocol_schemas(&mut schemas, &mut methods);
    // The Desktop runtime speaks Native exclusively. Register the complete
    // Native method registry last so colliding ACP adapter names (notably
    // session/new, session/list and session/delete) cannot leak ACP wire
    // shapes into the first-party runtime validator.
    register_native_method_registry(&mut schemas, &mut methods);
    register_native_notification_registry(&mut schemas, &mut methods);
    // Replay-carrying result schemas embed the raw schemars ServerNotification
    // definition; align its field names with the wire casing.
    for schema in schemas.values_mut() {
        camel_case_embedded_server_notification(schema);
    }

    ProtocolSchemaBundle { schemas, methods }
}

fn register_native_notification_registry(
    schemas: &mut BTreeMap<String, RootSchema>,
    methods: &mut BTreeMap<String, MethodSchemaBinding>,
) {
    let root = schemars::schema_for!(native::event::ServerNotification);
    let variants = root
        .schema
        .subschemas
        .as_ref()
        .and_then(|subschemas| subschemas.one_of.as_ref())
        .expect("ServerNotification is a tagged union");
    for variant in variants {
        let variant = variant.clone().into_object();
        let Some(object) = variant.object.as_ref() else {
            continue;
        };
        let Some(method_name) = object
            .properties
            .get("method")
            .cloned()
            .and_then(|schema| schema.into_object().enum_values)
            .and_then(|values| values.into_iter().next())
            .and_then(|value| value.as_str().map(str::to_owned))
        else {
            continue;
        };
        let Some(params) = object.properties.get("params") else {
            continue;
        };
        let mut params = params.clone().into_object();
        camel_case_params_fields(&mut params);
        let schema_name = format!(
            "{}NotificationParams",
            method_name
                .split(|character: char| !character.is_ascii_alphanumeric())
                .filter(|segment| !segment.is_empty())
                .map(|segment| {
                    let mut characters = segment.chars();
                    characters
                        .next()
                        .map(|first| first.to_ascii_uppercase().to_string())
                        .unwrap_or_default()
                        + characters.as_str()
                })
                .collect::<String>()
        );
        params.metadata().title = Some(schema_name.clone());
        schemas.insert(
            schema_name.clone(),
            RootSchema {
                meta_schema: root.meta_schema.clone(),
                schema: params,
                definitions: root.definitions.clone(),
            },
        );
        methods
            .entry(method_name)
            .or_default()
            .incoming_notification = Some(Box::leak(schema_name.into_boxed_str()));
    }
}

/// schemars 0.8 does not honor serde's `rename_all_fields`, so generated
/// schema objects keep Rust field names (`restore_plan_id`) while the wire
/// serializes camelCase (`restorePlanId`). Rewrite a notification params
/// schema's field names so validation accepts what the server actually sends.
fn camel_case_params_fields(params: &mut schemars::schema::SchemaObject) {
    if let Some(object) = params.object.as_mut() {
        object.properties = std::mem::take(&mut object.properties)
            .into_iter()
            .map(|(name, schema)| (snake_to_lower_camel(&name), schema))
            .collect();
        object.required = std::mem::take(&mut object.required)
            .into_iter()
            .map(|name| snake_to_lower_camel(&name))
            .collect();
    }
}

/// Apply the same rewrite to the `ServerNotification` definition embedded in
/// replay-carrying result schemas (`SubscriptionCreateResult`). The registry
/// path above already rewrites its standalone copies; without this pass the
/// embedded definition keeps snake_case field names and replay envelope
/// validation rejects every notification whose variant fields are multi-word.
fn camel_case_embedded_server_notification(schema: &mut RootSchema) {
    let Some(definition) = schema.definitions.get_mut("ServerNotification") else {
        return;
    };
    let schemars::schema::Schema::Object(object) = definition else {
        return;
    };
    let Some(subschemas) = object.subschemas.as_mut() else {
        return;
    };
    let Some(branches) = subschemas.one_of.as_mut() else {
        return;
    };
    for branch in branches {
        let schemars::schema::Schema::Object(branch_object) = branch else {
            continue;
        };
        let Some(validation) = branch_object.object.as_mut() else {
            continue;
        };
        let Some(params) = validation.properties.get_mut("params") else {
            continue;
        };
        let schemars::schema::Schema::Object(params_object) = params else {
            continue;
        };
        camel_case_params_fields(params_object);
    }
}

fn snake_to_lower_camel(value: &str) -> String {
    let mut segments = value.split('_');
    let mut result = segments.next().unwrap_or_default().to_string();
    for segment in segments {
        let mut characters = segment.chars();
        if let Some(first) = characters.next() {
            result.push(first.to_ascii_uppercase());
            result.push_str(characters.as_str());
        }
    }
    result
}

/// Write the first-party Native TypeScript wire types to `output_dir`.
pub fn write_native_typescript_dir(output_dir: impl AsRef<Path>) -> io::Result<()> {
    let output_dir = output_dir.as_ref();
    if output_dir.exists() {
        fs::remove_dir_all(output_dir)?;
    }
    fs::create_dir_all(output_dir)?;
    fs::write(output_dir.join("native.ts"), generate_protocol_typescript())?;
    fs::write(
        output_dir.join("schema.json"),
        generate_protocol_schema_json(),
    )?;
    fs::write(output_dir.join("index.ts"), NATIVE_INDEX_TS)?;
    Ok(())
}

fn register_native_method_registry(
    schemas: &mut BTreeMap<String, RootSchema>,
    methods: &mut BTreeMap<String, MethodSchemaBinding>,
) {
    for spec in native::methods::NATIVE_METHODS {
        // Connection negotiation deliberately retains the compatibility
        // initialize envelope; `_meta.devo.protocol = native` selects the
        // Native method surface after negotiation.
        if spec.name == ACP_INITIALIZE_METHOD {
            continue;
        }
        let params = (spec.params_schema)();
        let result = (spec.result_schema)();
        let params_name = root_schema_name(&params);
        let result_name = root_schema_name(&result);
        schemas.insert(params_name.clone(), params);
        schemas.insert(result_name.clone(), result);
        method(
            methods,
            spec.name,
            MethodSchemaBinding {
                outgoing_request: Some(Box::leak(params_name.into_boxed_str())),
                incoming_result: Some(Box::leak(result_name.into_boxed_str())),
                ..MethodSchemaBinding::default()
            },
        );
    }
    for spec in native::methods::REVERSE_METHODS {
        let params = (spec.params_schema)();
        let result = (spec.result_schema)();
        let params_name = root_schema_name(&params);
        let result_name = root_schema_name(&result);
        schemas.insert(params_name.clone(), params);
        schemas.insert(result_name.clone(), result);
        method(
            methods,
            spec.name,
            MethodSchemaBinding {
                incoming_request: Some(Box::leak(params_name.into_boxed_str())),
                outgoing_response: Some(Box::leak(result_name.into_boxed_str())),
                ..MethodSchemaBinding::default()
            },
        );
    }
}

fn root_schema_name(schema: &RootSchema) -> String {
    schema
        .schema
        .metadata
        .as_ref()
        .and_then(|metadata| metadata.title.clone())
        .expect("registered Native schemas have titles")
}

fn register_acp_schemas(
    schemas: &mut BTreeMap<String, RootSchema>,
    methods: &mut BTreeMap<String, MethodSchemaBinding>,
) {
    schema::<AcpInitializeParams>(schemas);
    schema::<AcpInitializeResult>(schemas);
    schema::<AcpAuthenticateParams>(schemas);
    schema_named::<AcpEmptyAuthResult>("AcpAuthenticateResult", schemas);
    schema_named::<AcpEmptyAuthResult>("AcpLogoutParams", schemas);
    schema_named::<AcpLogoutResult>("AcpLogoutResult", schemas);
    schema::<AcpListSessionsParams>(schemas);
    schema::<AcpListSessionsResult>(schemas);
    schema::<AcpNewSessionParams>(schemas);
    schema::<AcpNewSessionResult>(schemas);
    schema::<AcpLoadSessionParams>(schemas);
    schema::<AcpLoadSessionResult>(schemas);
    schema::<AcpResumeSessionParams>(schemas);
    schema_named::<AcpLoadSessionResult>("AcpResumeSessionResult", schemas);
    schema::<AcpSessionActionParams>(schemas);
    schema_named::<AcpSessionActionParams>("AcpDeleteSessionParams", schemas);
    schema_named::<AcpSessionActionParams>("AcpCloseSessionParams", schemas);
    schema::<AcpEmptyResult>(schemas);
    schema_named::<AcpEmptyResult>("AcpDeleteSessionResult", schemas);
    schema_named::<AcpEmptyResult>("AcpCloseSessionResult", schemas);
    schema::<AcpPromptParams>(schemas);
    schema::<AcpPromptResult>(schemas);
    schema::<AcpCancelParams>(schemas);
    schema::<AcpSetModeParams>(schemas);
    schema_named::<AcpEmptyResult>("AcpSetModeResult", schemas);
    schema::<AcpSetConfigOptionParams>(schemas);
    schema::<AcpSetConfigOptionResult>(schemas);
    schema::<AcpSessionNotification>(schemas);
    schema::<AcpRequestPermissionParams>(schemas);
    schema::<AcpRequestPermissionResponse>(schemas);
    schema::<AcpFsReadTextFileParams>(schemas);
    schema::<AcpFsReadTextFileResult>(schemas);
    schema::<AcpFsWriteTextFileParams>(schemas);

    method(
        methods,
        ACP_INITIALIZE_METHOD,
        MethodSchemaBinding {
            outgoing_request: Some("AcpInitializeParams"),
            incoming_result: Some("AcpInitializeResult"),
            ..MethodSchemaBinding::default()
        },
    );
    method(
        methods,
        ACP_AUTHENTICATE_METHOD,
        MethodSchemaBinding {
            outgoing_request: Some("AcpAuthenticateParams"),
            incoming_result: Some("AcpAuthenticateResult"),
            ..MethodSchemaBinding::default()
        },
    );
    method(
        methods,
        ACP_LOGOUT_METHOD,
        MethodSchemaBinding {
            outgoing_request: Some("AcpLogoutParams"),
            incoming_result: Some("AcpLogoutResult"),
            ..MethodSchemaBinding::default()
        },
    );
    method(
        methods,
        ACP_SESSION_LIST_METHOD,
        MethodSchemaBinding {
            outgoing_request: Some("AcpListSessionsParams"),
            incoming_result: Some("AcpListSessionsResult"),
            ..MethodSchemaBinding::default()
        },
    );
    method(
        methods,
        ACP_SESSION_NEW_METHOD,
        MethodSchemaBinding {
            outgoing_request: Some("AcpNewSessionParams"),
            incoming_result: Some("AcpNewSessionResult"),
            ..MethodSchemaBinding::default()
        },
    );
    method(
        methods,
        ACP_SESSION_LOAD_METHOD,
        MethodSchemaBinding {
            outgoing_request: Some("AcpLoadSessionParams"),
            incoming_result: Some("AcpLoadSessionResult"),
            ..MethodSchemaBinding::default()
        },
    );
    method(
        methods,
        ACP_SESSION_RESUME_METHOD,
        MethodSchemaBinding {
            outgoing_request: Some("AcpResumeSessionParams"),
            incoming_result: Some("AcpResumeSessionResult"),
            ..MethodSchemaBinding::default()
        },
    );
    method(
        methods,
        ACP_SESSION_CLOSE_METHOD,
        MethodSchemaBinding {
            outgoing_request: Some("AcpCloseSessionParams"),
            incoming_result: Some("AcpCloseSessionResult"),
            ..MethodSchemaBinding::default()
        },
    );
    method(
        methods,
        ACP_SESSION_DELETE_METHOD,
        MethodSchemaBinding {
            outgoing_request: Some("AcpDeleteSessionParams"),
            incoming_result: Some("AcpDeleteSessionResult"),
            ..MethodSchemaBinding::default()
        },
    );
    method(
        methods,
        ACP_SESSION_PROMPT_METHOD,
        MethodSchemaBinding {
            outgoing_request: Some("AcpPromptParams"),
            incoming_result: Some("AcpPromptResult"),
            ..MethodSchemaBinding::default()
        },
    );
    method(
        methods,
        ACP_SESSION_CANCEL_METHOD,
        MethodSchemaBinding {
            outgoing_notification: Some("AcpCancelParams"),
            ..MethodSchemaBinding::default()
        },
    );
    method(
        methods,
        ACP_SESSION_SET_MODE_METHOD,
        MethodSchemaBinding {
            outgoing_request: Some("AcpSetModeParams"),
            incoming_result: Some("AcpSetModeResult"),
            ..MethodSchemaBinding::default()
        },
    );
    method(
        methods,
        ACP_SESSION_SET_CONFIG_OPTION_METHOD,
        MethodSchemaBinding {
            outgoing_request: Some("AcpSetConfigOptionParams"),
            incoming_result: Some("AcpSetConfigOptionResult"),
            ..MethodSchemaBinding::default()
        },
    );
    method(
        methods,
        ACP_SESSION_UPDATE_METHOD,
        MethodSchemaBinding {
            incoming_notification: Some("AcpSessionNotification"),
            ..MethodSchemaBinding::default()
        },
    );
    method(
        methods,
        ACP_SESSION_REQUEST_PERMISSION_METHOD,
        MethodSchemaBinding {
            incoming_request: Some("AcpRequestPermissionParams"),
            outgoing_response: Some("AcpRequestPermissionResponse"),
            ..MethodSchemaBinding::default()
        },
    );
    method(
        methods,
        ACP_FS_READ_TEXT_FILE_METHOD,
        MethodSchemaBinding {
            incoming_request: Some("AcpFsReadTextFileParams"),
            outgoing_response: Some("AcpFsReadTextFileResult"),
            ..MethodSchemaBinding::default()
        },
    );
    method(
        methods,
        ACP_FS_WRITE_TEXT_FILE_METHOD,
        MethodSchemaBinding {
            incoming_request: Some("AcpFsWriteTextFileParams"),
            outgoing_response: Some("AcpEmptyResult"),
            ..MethodSchemaBinding::default()
        },
    );
}

fn register_devo_protocol_schemas(
    schemas: &mut BTreeMap<String, RootSchema>,
    methods: &mut BTreeMap<String, MethodSchemaBinding>,
) {
    schema::<SessionStartParams>(schemas);
    schema::<SessionStartResult>(schemas);
    schema::<SessionResumeParams>(schemas);
    schema::<SessionResumeResult>(schemas);
    schema::<native::rpc_session::SessionForkCut>(schemas);
    schema::<native::rpc_session::SessionForkParams>(schemas);
    schema::<native::rpc_session::SessionForkResult>(schemas);
    schema::<native::rpc_admin::SkillListParams>(schemas);
    schema::<native::rpc_admin::SkillListResult>(schemas);
    schema::<native::rpc_admin::SkillInfo>(schemas);
    schema::<native::rpc_admin::SkillSetEnabledParams>(schemas);
    schema::<native::rpc_admin::SkillSetEnabledResult>(schemas);
    schema::<McpListParams>(schemas);
    schema::<McpServerInfo>(schemas);
    schema::<McpListResult>(schemas);
    schema::<McpToolsParams>(schemas);
    schema::<McpToolEntry>(schemas);
    schema::<McpToolsResult>(schemas);
    schema::<McpSetEnabledParams>(schemas);
    schema::<McpSetEnabledResult>(schemas);
    schema::<ContextUsageReadParams>(schemas);
    schema::<ContextUsageReadResult>(schemas);
    schema::<CommandExecParams>(schemas);
    schema::<CommandExecResult>(schemas);
    schema::<CommandExecWriteParams>(schemas);
    schema::<CommandExecWriteResult>(schemas);
    schema::<CommandExecResizeParams>(schemas);
    schema::<CommandExecResizeResult>(schemas);
    schema::<CommandExecTerminateParams>(schemas);
    schema::<CommandExecTerminateResult>(schemas);
    schema::<TurnStartParams>(schemas);
    schema::<crate::native::rpc_turn::TurnRecovery>(schemas);
    schema::<crate::native::rpc_turn::TurnRecoveryReadParams>(schemas);
    schema::<crate::native::rpc_turn::TurnRecoveryReadResult>(schemas);
    schema::<crate::native::rpc_turn::TurnResumeParams>(schemas);
    schema::<crate::native::rpc_turn::TurnResumeResult>(schemas);

    schema::<TurnStartResult>(schemas);
    schema::<native::rpc_session::SessionInterruptScope>(schemas);
    schema::<native::rpc_session::SessionInterruptParams>(schemas);
    schema::<native::rpc_session::SessionInterruptResult>(schemas);
    schema::<native::rpc_workspace::WorkspaceChangesReadParams>(schemas);
    schema::<native::rpc_workspace::WorkspaceChangesReadResult>(schemas);
    schema::<native::event::WorkspaceChangeStatsNotification>(schemas);
    schema::<native::event::WorkspaceChangesUpdatedNotification>(schemas);
    schema::<native::item::Item>(schemas);
    schema::<native::methods::UserInputRespondParams>(schemas);
    schema::<native::rpc_search::SearchStartParams>(schemas);
    schema::<native::rpc_search::SearchStartResult>(schemas);
    schema::<native::rpc_search::SearchUpdateParams>(schemas);
    schema::<native::rpc_search::SearchUpdateResult>(schemas);
    schema::<native::rpc_search::SearchCancelParams>(schemas);
    schema::<native::rpc_search::SearchCancelResult>(schemas);
    schema::<native::rpc_search::SearchSnapshot>(schemas);
    schema::<native::rpc_search::SearchResult>(schemas);
    schema::<native::rpc_search::SearchResultKind>(schemas);
    schema::<native::rpc_search::SearchFailedPayload>(schemas);
    schema::<SpawnAgentParams>(schemas);
    schema::<SpawnAgentResult>(schemas);
    schema::<AgentMessageParams>(schemas);
    schema::<AgentMessageResult>(schemas);
    schema::<WaitAgentParams>(schemas);
    schema::<WaitAgentResult>(schemas);
    schema::<AgentListParams>(schemas);
    schema::<AgentListResult>(schemas);
    schema::<AgentStatusParams>(schemas);
    schema::<AgentInfo>(schemas);
    schema::<TaskId>(schemas);
    schema::<TaskState>(schemas);
    schema::<TaskKind>(schemas);
    schema::<AgentTaskMetadata>(schemas);
    schema::<CommandTaskMetadata>(schemas);
    schema::<TaskInfo>(schemas);
    schema::<AwaitTaskParams>(schemas);
    schema::<AwaitTaskResult>(schemas);
    schema::<ListTasksParams>(schemas);
    schema::<ListTasksResult>(schemas);
    schema::<CancelTaskParams>(schemas);
    schema::<CancelTaskResult>(schemas);
    schema::<CloseAgentParams>(schemas);
    schema::<CloseAgentResult>(schemas);

    schema::<native::rpc_admin::ProviderListParams>(schemas);
    schema::<native::rpc_admin::ProviderListResult>(schemas);
    schema::<native::rpc_admin::ProviderUpsertParams>(schemas);
    schema::<native::rpc_admin::ProviderUpsertResult>(schemas);
    schema::<native::rpc_admin::ProviderDisconnectParams>(schemas);
    schema::<native::rpc_admin::ProviderDisconnectResult>(schemas);
    schema::<native::rpc_admin::ProviderModelRemoveParams>(schemas);
    schema::<native::rpc_admin::ProviderModelRemoveResult>(schemas);
    schema::<native::rpc_admin::ProviderValidateParams>(schemas);
    schema::<native::rpc_admin::ProviderValidateResult>(schemas);
    schema::<native::rpc_admin::ProviderDiscoverParams>(schemas);
    schema::<native::rpc_admin::ProviderDiscoverResult>(schemas);

    method(
        methods,
        "session/start",
        MethodSchemaBinding {
            outgoing_request: Some("SessionStartParams"),
            incoming_result: Some("SessionStartResult"),
            ..MethodSchemaBinding::default()
        },
    );
    native_method::<SessionResumeParams, SessionResumeResult>(methods, "session/resume");
    native_method::<native::rpc_session::SessionForkParams, native::rpc_session::SessionForkResult>(
        methods,
        "session/fork",
    );
    native_method::<native::rpc_admin::SkillListParams, native::rpc_admin::SkillListResult>(
        methods,
        "skill/list",
    );
    native_method::<
        native::rpc_admin::SkillSetEnabledParams,
        native::rpc_admin::SkillSetEnabledResult,
    >(methods, "skill/set_enabled");
    native_method::<McpListParams, McpListResult>(methods, "mcp/list");
    native_method::<McpToolsParams, McpToolsResult>(methods, "mcp/tools");
    native_method::<McpSetEnabledParams, McpSetEnabledResult>(methods, "mcp/set_enabled");
    native_method::<ContextUsageReadParams, ContextUsageReadResult>(methods, "context/usage/read");
    native_method::<CommandExecParams, CommandExecResult>(methods, "command/exec");
    native_method::<TurnStartParams, TurnStartResult>(methods, "turn/start");
    native_method::<
        crate::native::rpc_turn::TurnResumeParams,
        crate::native::rpc_turn::TurnResumeResult,
    >(methods, "turn/resume");
    native_method::<
        crate::native::rpc_turn::TurnRecoveryReadParams,
        crate::native::rpc_turn::TurnRecoveryReadResult,
    >(methods, "turn/recovery/read");
    native_method::<
        native::rpc_session::SessionInterruptParams,
        native::rpc_session::SessionInterruptResult,
    >(methods, "session/interrupt");
    native_method::<
        native::rpc_workspace::WorkspaceChangesReadParams,
        native::rpc_workspace::WorkspaceChangesReadResult,
    >(methods, "workspace/changes/read");
    method(
        methods,
        "workspace/changes/updated",
        MethodSchemaBinding {
            incoming_notification: Some("WorkspaceChangesUpdatedNotification"),
            ..MethodSchemaBinding::default()
        },
    );
    native_method::<native::rpc_search::SearchStartParams, native::rpc_search::SearchStartResult>(
        methods,
        "search/start",
    );
    native_method::<native::rpc_search::SearchUpdateParams, native::rpc_search::SearchUpdateResult>(
        methods,
        "search/update",
    );
    native_method::<native::rpc_search::SearchCancelParams, native::rpc_search::SearchCancelResult>(
        methods,
        "search/cancel",
    );
    native_method::<native::rpc_admin::ProviderListParams, native::rpc_admin::ProviderListResult>(
        methods,
        "provider/list",
    );
    native_method::<
        native::rpc_admin::ProviderValidateParams,
        native::rpc_admin::ProviderValidateResult,
    >(methods, "provider/validate");
    native_method::<native::rpc_admin::ProviderUpsertParams, native::rpc_admin::ProviderUpsertResult>(
        methods,
        "provider/upsert",
    );
    native_method::<
        native::rpc_admin::ProviderDisconnectParams,
        native::rpc_admin::ProviderDisconnectResult,
    >(methods, "provider/disconnect");
    native_method::<
        native::rpc_admin::ProviderModelRemoveParams,
        native::rpc_admin::ProviderModelRemoveResult,
    >(methods, "provider/model/remove");
}

fn method(
    methods: &mut BTreeMap<String, MethodSchemaBinding>,
    method: impl Into<String>,
    binding: MethodSchemaBinding,
) {
    methods.insert(method.into(), binding);
}

fn native_method<P: JsonSchema, R: JsonSchema>(
    methods: &mut BTreeMap<String, MethodSchemaBinding>,
    method_name: &'static str,
) {
    method(
        methods,
        method_name,
        MethodSchemaBinding {
            outgoing_request: Some(Box::leak(P::schema_name().into_boxed_str())),
            incoming_result: Some(Box::leak(R::schema_name().into_boxed_str())),
            ..MethodSchemaBinding::default()
        },
    );
}

fn schema<T: JsonSchema>(schemas: &mut BTreeMap<String, RootSchema>) {
    schema_named::<T>(&T::schema_name(), schemas);
}

fn schema_named<T: JsonSchema>(name: &str, schemas: &mut BTreeMap<String, RootSchema>) {
    let mut schema = schemars::schema_for!(T);
    schema.schema.metadata().title = Some(name.to_string());
    schemas.insert(name.to_string(), schema);
}
