// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Phase of a provider retry cycle (ratified vocabulary, L2-DES-APP-009
 * DD-3): a retry is first `Scheduled`, then `Resumed` when the next attempt
 * starts.
 */
export type ModelQueryRetryPhase = "scheduled" | "resumed";
