// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelQueryRetryPhase } from "./ModelQueryRetryPhase";

export type TurnProviderRetryStatusPayload = { session_id: SessionId, turn_id: TurnId, attempt: number, max_attempts?: number | null, backoff_ms: bigint, provider: string, model: string, 
/**
 * Native retry phase vocabulary (no separate protocol-level dual).
 */
phase: ModelQueryRetryPhase, message: string, };
